<template>
  <div class="stack">
    <img
      width="55"
      src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/HTML5_Badge.svg/2048px-HTML5_Badge.svg.png"
    />
    <img
      width="55"
      src="https://cdn.pixabay.com/photo/2017/08/05/11/16/logo-2582747_1280.png"
    />
    <img
      width="55"
      src="https://raw.githubusercontent.com/gilbarbara/logos/master/logos/apollostack.svg"
    /><img
      width="55"
      src="https://raw.githubusercontent.com/gilbarbara/logos/master/logos/element.svg"
    /><img
      width="55"
      src="https://raw.githubusercontent.com/gilbarbara/logos/master/logos/eslint.svg"
    /><img
      width="55"
      src="https://raw.githubusercontent.com/gilbarbara/logos/master/logos/graphql.svg"
    /><img
      width="55"
      src="https://raw.githubusercontent.com/gilbarbara/logos/master/logos/javascript.svg"
    /><img
      width="55"
      src="https://raw.githubusercontent.com/gilbarbara/logos/master/logos/prettier.svg"
    /><img
      width="55"
      src="https://raw.githubusercontent.com/gilbarbara/logos/master/logos/react.svg"
    /><img
      width="55"
      src="https://raw.githubusercontent.com/gilbarbara/logos/master/logos/sass.svg"
    /><img
      width="55"
      src="https://raw.githubusercontent.com/gilbarbara/logos/master/logos/typescript-icon.svg"
    /><img
      width="55"
      src="https://raw.githubusercontent.com/gilbarbara/logos/master/logos/vue.svg"
    />
    <img
      width="55"
      src="https://raw.githubusercontent.com/gilbarbara/logos/master/logos/node-sass.svg"
    />
    <img
      width="55"
      src="https://raw.githubusercontent.com/gilbarbara/logos/master/logos/airtable.svg"
    /><img
      width="55"
      src="https://ui-lib.com/blog/wp-content/uploads/2021/12/nextjs-boilerplate-logo.png"
    /><img
      width="55"
      src="https://raw.githubusercontent.com/gilbarbara/logos/master/logos/postcss.svg"
    /><img
      width="55"
      src="https://seeklogo.com/images/T/tailwind-css-logo-5AD4175897-seeklogo.com.png"
    /><img
      width="55"
      src="https://raw.githubusercontent.com/gilbarbara/logos/master/logos/nodejs.svg"
    />
  </div>
</template>
